services:
  postgres:
    image: postgres:13
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - kitty-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

  backend:
    # build:
    #   context: ./backend
    #   dockerfile: ./Dockerfile
    image: ${DOCKER_USER}/kittygram_backend:latest
    container_name: backend
    restart: always
    env_file:
      - .env
    volumes:
      - ./backend/static:/app/static
      - ./backend/media:/app/media
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - kitty-net

  frontend:
    # build:
    #   context: ./frontend
    #   dockerfile: ./Dockerfile
    image: ${DOCKER_USER}/kittygram_frontend:latest
    container_name: frontend
    restart: always
    volumes:
      - static:/app/build
    depends_on:
      - backend
    networks:
      - kitty-net

  nginx:
    # build:
    #   context: ./nginx
    #   dockerfile: ./Dockerfile
    image: ${DOCKER_USER}/kittygram_gateway:latest
    container_name: gateway
    restart: always
    depends_on:
      - backend
      - frontend
    ports:
      - "8080:80"
    volumes:
      - ./backend/static:/static:ro
      - ./backend/media:/media:ro
    networks:
      - kitty-net

volumes:
  static:
  media:
  postgres-data:

networks:
  kitty-net:
